- hosts: localhost
  gather_facts: False
  tasks:
    - name: Importing vpc variables 
      include_vars: var/vpc_variable.yml

    - name: create a VPC with dedicated tenancy and a couple of tags
      ec2_vpc_net:
        name: "{{vpcName}}"
        cidr_block: "{{vpcCIDR}}"
        region: "{{region}}"
        state: "{{state}}"
        dns_support: yes
        dns_hostnames: yes
      register: vpcOut

    - name: Create public subnet 1 
      ec2_vpc_subnet:
        region: "{{region}}"
        state: "{{state}}"
        vpc_id: "{{vpcOut.vpc.id}}"
        cidr: "{{pubSub1CIDR}}"
        az: "{{az1}}"
        map_public: yes
        tags:
          Name: Vprofile Public Subnet 1
      register: pubSub1Out  

    - name: Create public subnet 2 
      ec2_vpc_subnet:
        region: "{{region}}"
        state: "{{state}}"
        vpc_id: "{{vpcOut.vpc.id}}"
        cidr: "{{pubSub2CIDR}}"
        az: "{{az2}}"
        map_public: yes
        tags:
          Name: Vprofile Public Subnet 2
      register: pubSub2Out  
      
    - name: Create public subnet 3 
      ec2_vpc_subnet:
        region: "{{region}}"
        state: "{{state}}"
        vpc_id: "{{vpcOut.vpc.id}}"
        cidr: "{{pubSub3CIDR}}"
        az: "{{az3}}"
        map_public: yes
        tags:
          Name: Vprofile Public Subnet 3
      register: pubSub3Out  

    - name: Create private subnet 1
      ec2_vpc_subnet:
        region: "{{region}}"
        state: "{{state}}"
        vpc_id: "{{vpcOut.vpc.id}}"
        cidr: "{{pvtSub1CIDR}}"
        az: "{{az1}}"
        tags:
          Name: Vprofile Private Subnet 1
      register: pvtSub1Out  

    - name: Create private subnet 2
      ec2_vpc_subnet:
        region: "{{region}}"
        state: "{{state}}"
        vpc_id: "{{vpcOut.vpc.id}}"
        cidr: "{{pvtSub2CIDR}}"
        az: "{{az2}}"
        tags:
          Name: Vprofile Private Subnet 2
      register: pvtSub2Out  

    - name: Create private subnet 3
      ec2_vpc_subnet:
        region: "{{region}}"
        state: "{{state}}"
        vpc_id: "{{vpcOut.vpc.id}}"
        cidr: "{{pvtSub3CIDR}}"
        az: "{{az3}}"
        tags:
          Name: Vprofile Private Subnet 3
      register: pvtSub3Out  

    - name: Create Internet gateway with tags
      ec2_vpc_igw:
        vpc_id: "{{vpcOut.vpc.id}}"
        region: "{{region}}"
        state: "{{state}}"
        tags:
            Name: Vprofile IGW
      register: igwOut  

    - name: Set up public subnet route table 
      ec2_vpc_route_table:
        vpc_id: "{{vpcOut.vpc.id}}"
        region: "{{region}}"
        resource_tags:
          Name: Vprofile publicRT
        subnets:
          - "{{pubSub1Out.subnet.id}}"
          - "{{pubSub2Out.subnet.id}}"
          - "{{pubSub3Out.subnet.id}}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igwOut.gateway_id }}"
      register: pubRTOut   
    
    - name: Create new nat gateway in public subnets
      ec2_vpc_nat_gateway:
        state: "{{state}}"
        subnet_id: 
          - "{{pubSub1Out.subnet.id}}"
        region: "{{region}}"
        if_exist_do_not_create: true
        wait: true
      register: natOut

    - name: Set up private subnet route table 
      ec2_vpc_route_table:
        vpc_id: "{{vpcOut.vpc.id}}"
        region: "{{region}}"
        tags:
          Name: Vprofile publicRT
        subnets:
          - "{{pvtSub1Out.subnet.id}}"
          - "{{pvtSub2Out.subnet.id}}"
          - "{{pvtSub3Out.subnet.id}}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ natOut.nat_gateway_id }}"
      register: pvtRTOut