- hosts: localhost
  gather_facts: False
  tasks:
    - name: Importing vpc variables 
      include_vars: var/vpc_variable.yml

    - name: create a VPC with dedicated tenancy and a couple of tags
      ec2_vpc_net:
        name: "{{vpcName}}"
        cidr_block: "{{vpcCIDR}}"
        region: "{{region}}"
        state: "{{state}}"
        dns_support: yes
        dns_hostnames: yes
      register: vpcOut

    - name: Create public subnet 1 
      ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpcOut.vpc.id}}"
        cidr: "{{pubSub1CIDR}}"
        az: "{{az1}}"
        map_public: yes
        tags:
          Name: Public Subnet 1
      register: pubSub1Out  

    - name: Create public subnet 2 
      ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpcOut.vpc.id}}"
        cidr: "{{pubSub2CIDR}}"
        az: "{{az2}}"
        map_public: yes
        tags:
          Name: Public Subnet 2
      register: pubSub2Out  
      
    - name: Create public subnet 3 
      ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpcOut.vpc.id}}"
        cidr: "{{pubSub3CIDR}}"
        az: "{{az3}}"
        map_public: yes
        tags:
          Name: Public Subnet 3
      register: pubSub3Out  

    - name: Create private subnet 1
      ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpcOut.vpc.id}}"
        cidr: "{{pvtSub1CIDR}}"
        az: "{{az1}}"
        tags:
          Name: Private Subnet 1
      register: pvtSub1Out  

    - name: Create private subnet 2
      ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpcOut.vpc.id}}"
        cidr: "{{pvtSub2CIDR}}"
        az: "{{az2}}"
        tags:
          Name: Private Subnet 2
      register: pvtSub2Out  

    - name: Create private subnet 3
      ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpcOut.vpc.id}}"
        cidr: "{{pvtSub3CIDR}}"
        az: "{{az3}}"
        tags:
          Name: Private Subnet 3
      register: pvtSub3Out  