- hosts: localhost
  gather_facts: False
  tasks:
    - name: Importing resource id 
      include_vars: 
        file: ./var/resource_id.yml
        name: resources
    - name: Importing vpc variables 
      include_vars: 
        file: ./var/vpc_variable.yml
        name: VPCvariable    

# Getting the ssl certificate 
    - name: getting the ssl certificate we have to access 443 port
      aws_acm_info:
        region: "{{resources.Region}}"
        domain_name: "*.mydevop.co.in"
      register: ACMOut
    
    - debug:
        msg: "{{ACMOut}}"  

# Load Balancer
    - name: create an security group for Load Balancer
      ec2_group:
        name: vprofile-ELB
        description: sg for ELB
        vpc_id: "{{resources.VPC}}"
        region: "{{resources.Region}}"
        tags:
          Name: vprofileELB
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80          
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all traffic from port 80        
          - proto: tcp
            from_port: 443
            to_port: 443         
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all traffic from port 443           
      register: ELBSgOut

    - name: Create a target group with a default health check
      elb_target_group:
        name: vprofileTG
        region: "{{resources.Region}}"
        protocol: http
        port: 8080
        vpc_id: "{{resources.VPC}}"
        state: present

    # - name: Creating a load balance which will connect to all the private subnet and launch the required resources
    #   elb_application_lb:
    #     state: present
    #     name: 'VprofileELB'
    #     region: "{{resources.Region}}"
    #     zones:
    #       - "{{VPCvariable.az1}}"
    #       - "{{VPCvariable.az2}}"
    #       - "{{VPCvariable.az3}}"
    #     cross_az_load_balancing: "yes"
    #     security_group_ids: "{{ELBSgOut.group_id}}"
    #     subnets: 
    #       - "{{resources.PublicSubnet1}}"
    #       - "{{resources.PublicSubnet2}}"
    #       - "{{resources.PublicSubnet3}}"
    #     purge_subnets: yes
    #     listeners:
    #       - protocol: http
    #         load_balancer_port: 80
    #         instance_port: 80
    #       - protocol: https
    #         load_balancer_port: 443
    #         instance_port: 443
    #         ssl_certificate_id: ACMOut.certificates.certificate_arn

# Vprofile Stack
    - name: create an security group for Vprofile Stack
      ec2_group:
        name: vprofileStack
        description: sg for Vprofile Stack
        vpc_id: "{{resources.VPC}}"
        region: "{{resources.Region}}"
        tags:
          Name: vprofileStack
        purge_rules: no
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80          
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all traffic from port 80        
          - proto: tcp
            from_port: 443
            to_port: 443         
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all traffic from port 443                       
          - proto: tcp
            from_port: 22
            to_port: 22      
            # added this since while accessing the group_id it was getting timed out
            group_id: "{{resources.BastionSG_accID}}/{{resources.BastionSG_id}}/{{resources.BastionSG_name}}"
            rule_desc: allow ssh for bastion 
      register: VprofileSgOut

    - name: Update the SG for vprofile so that the components within the SG can talk to each other
      ec2_group:
        name: vprofileStack
        description: sg for Vprofile Stack
        vpc_id: "{{resources.VPC}}"
        region: "{{resources.Region}}"
        tags:
          Name: vprofileStack
        purge_rules: no 
        rules:
        # in the 'proto' attribute, if you specify  all, or a protocol number other than tcp, udp, icmp, or 58 (ICMPv6),
        # traffic on all ports is allowed, regardless of any ports you specify. So the port is not mentioned
          - proto: all
            # added this since while accessing the group_id it was getting timed out          
            group_id: "{{VprofileSgOut.owner_id}}/{{VprofileSgOut.group_id}}/{{VprofileSgOut.group_name}}"
            rule_desc: allow traffice from other EC2 instances within the security group
            

 