- hosts: localhost
  gather_facts: False
  tasks:
    - name: Importing resource id 
      include_vars: var/resource_id.yml

    - name: create an security group for Load Balancer
      ec2_group:
        name: "vprofile-ELB"
        description: sg for ELB
        vpc_id: "{{VPC}}"
        region: "{{Region}}"
        tags:
          Name: vprofile-ELB
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80          
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all traffic from port 80        
          
          - proto: tcp
            from_port: 443
            to_port: 443         
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all traffic from port 443           
      register: ELBSgOut
  

    - name: create an security group for Vprofile Stack in private subnet
      ec2_group:
        name: "vprofileStack"
        description: sg for ELB
        vpc_id: "{{VPC}}"
        region: "{{Region}}"
        tags:
          Name: vprofileStack
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22          
            group_id: "{{ELBSgOut.group_id}}"
            rule_desc: allow ssh for bastion 

          - proto: tcp
            from_port: 80
            to_port: 80          
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all traffic from port 80        
          
          - proto: tcp
            from_port: 443
            to_port: 443         
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all traffic from port 443                       
      register: VprofileSgOut

    - name: Update the SG for vprofile so that the components within the SG can talk to each other
      ec2_group:
        name: "vprofileStack"
        description: sg for ELB
        vpc_id: "{{VPC}}"
        region: "{{Region}}"
        tags:
          Name: vprofileStack
        purge_rules: no 
        rules:
        # in the 'proto' attribute, if you specify  all, or a protocol number other than tcp, udp, icmp, or 58 (ICMPv6),
        # traffic on all ports is allowed, regardless of any ports you specify. So the port is not mentioned
          - proto: all
            group_id: "{{VprofileSgOut.group_id}}"
            rule_desc: allow resources within the security group to talk to each other
      register: VprofileSgOut





 